version: '3.3'
services:
  redis:
    image: redis
  rabbitmq:
    image: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=CurrencyApp
      - RABBITMQ_DEFAULT_PASS=CurrencyApp
      - RABBITMQ_DEFAULT_VHOST=CurrencyApp
    ports:
      - "21001:5672"
      - "21002:15672"
  db:
    image: postgres
    environment:
      - POSTGRES_USER=CurrencyApp
      - POSTGRES_PASSWORD=CurrencyApp
      - POSTGRES_DB=CurrencyApp
    ports:
      - "21003:5432"
  web:
    build: .
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - .:/code
    links:
      - db
      - redis
      - rabbitmq
    depends_on:
      - db
      - redis
      - rabbitmq
  celery:
    restart: always
    build:
      context: .
    command: celery -A CurrencyApp worker -l info
    volumes:
      - .:/code

